export interface Garment {
  id: string;
  name: string;
  description: string;
  fabric_info: string;
  image_filename: string;
  like_count: number;
  category: "women" | "men" | "accessories" | "bridal";
  subcategory: string;
  on_sale?: boolean;
}

const garments: Garment[] = [
  // ── SAREES (20) ──
  { id: "g01", name: "Banarasi Silk Saree — Crimson & Gold", description: "Woven in the ancient city of looms, every inch of this brocade sings with Mughal garden motifs. Gold zari on crimson silk — a drape that carries five centuries of mastery in its folds.", fabric_info: "Pure Banarasi Silk, Gold Zari", image_filename: "banarasi_silk_crimson_gold.jpg", like_count: 487, category: "women", subcategory: "Sarees" },
  { id: "g02", name: "Kanchipuram Temple Border Saree", description: "Woven with over ten thousand silk threads. The temple gopuram border rises along the pallu like sacred architecture rendered in fabric. To wear this saree is to wear a prayer.", fabric_info: "Pure Kanchipuram Silk", image_filename: "kanchipuram_temple_border.jpg", like_count: 534, category: "women", subcategory: "Sarees" },
  { id: "g03", name: "Chanderi Tissue Saree — Ivory", description: "So fine it could pass through a ring. Chanderi's legendary transparency meets tiny gold butis — a garment that weighs almost nothing but carries the weight of centuries.", fabric_info: "Chanderi Silk-Cotton Tissue", image_filename: "chanderi_tissue_ivory.jpg", like_count: 312, category: "women", subcategory: "Sarees" },
  { id: "g04", name: "Pochampally Ikat Silk Saree", description: "Resist-dyed threads woven into diamond geometry. Each pattern slightly imperfect — proof that human hands, not machines, orchestrated this symphony of indigo and amber.", fabric_info: "Silk, Double Ikat Weave", image_filename: "pochampally_ikat_silk.jpg", like_count: 278, category: "women", subcategory: "Sarees", on_sale: true },
  { id: "g05", name: "Paithani Peacock Pallu Saree", description: "Peacocks frozen mid-dance in threads of emerald and gold. This ancient weaving takes over three months per saree — each feather a testament to human patience.", fabric_info: "Pure Silk, Handwoven Zari", image_filename: "paithani_peacock_pallu.jpg", like_count: 456, category: "women", subcategory: "Sarees" },
  { id: "g06", name: "Tussar Silk Saree — Natural Gold", description: "Wild silk harvested from forest cocoons, carrying the warmth of autumn in every thread. The natural golden sheen needs no embellishment — nature did the designing.", fabric_info: "Tussar Silk, Natural Dye", image_filename: "tussar_silk_natural_gold.jpg", like_count: 201, category: "women", subcategory: "Sarees", on_sale: true },
  { id: "g07", name: "Jamdani Muslin Saree", description: "The muslin that made emperors weep. So fine it was once called 'woven air.' Supplementary weft creates floating motifs — flowers growing not in gardens, but in fabric.", fabric_info: "Jamdani Muslin, Handwoven", image_filename: "jamdani_muslin_white.jpg", like_count: 345, category: "women", subcategory: "Sarees" },
  { id: "g08", name: "Patola Double-Ikat Saree", description: "Both warp and weft resist-dyed before weaving — the mathematical precision is staggering. A single saree takes six months. The patterns align perfectly. Every. Single. Time.", fabric_info: "Pure Silk, Double Ikat", image_filename: "patola_double_ikat.jpg", like_count: 467, category: "women", subcategory: "Sarees" },
  { id: "g09", name: "Gadwal Silk-Cotton Saree", description: "A cotton body meets a silk border in a union perfected over generations. The contrasting pallu appears to float — a visual trick that only hand-weavers can achieve.", fabric_info: "Silk-Cotton, Zari Border", image_filename: "gadwal_silk_cotton.jpg", like_count: 189, category: "women", subcategory: "Sarees", on_sale: true },
  { id: "g10", name: "Bandhani Tie-Dye Saree — Red", description: "Ten thousand tiny knots tied by hand, then dipped in colour. When untied, each knot leaves a dot — and ten thousand dots become a galaxy of crimson and gold.", fabric_info: "Georgette, Bandhani Tie-Dye", image_filename: "bandhani_tiedye_red.jpg", like_count: 267, category: "women", subcategory: "Sarees" },
  { id: "g11", name: "Maheshwari Silk Saree — Grape", description: "A reversible weave showing different patterns on each side. The weavers say the fabric has two faces — one for the world, one for the wearer. Both are beautiful.", fabric_info: "Silk-Cotton, Reversible Weave", image_filename: "maheshwari_silk_grape.jpg", like_count: 198, category: "women", subcategory: "Sarees" },
  { id: "g12", name: "Organza Saree — Blush Ombré", description: "Sheer organza graduating from dawn-pink to deep rose. When draped, the fabric moves like watercolour bleeding across paper — soft, unpredictable, utterly romantic.", fabric_info: "Organza, Ombré Dyed", image_filename: "organza_blush_ombre.jpg", like_count: 298, category: "women", subcategory: "Sarees" },
  { id: "g13", name: "Tant Cotton Saree — Bengal Stripe", description: "Thread-count so high the cotton behaves like silk. Bold stripes in vermillion and white — the confidence of simplicity.", fabric_info: "Tant Cotton, Handwoven", image_filename: "tant_cotton_bengal_stripe.jpg", like_count: 178, category: "women", subcategory: "Sarees", on_sale: true },
  { id: "g14", name: "Narayanpet Cotton Saree", description: "Handwoven cotton with interlocked weft border in maroon and gold. Temple motif pallu crowns the drape. Lightweight enough for daily wear, striking enough for an occasion.", fabric_info: "Pure Cotton, Temple Border", image_filename: "narayanpet_cotton_temple.jpg", like_count: 156, category: "women", subcategory: "Sarees" },
  { id: "g15", name: "Kasavu Set Mundu — Off-White & Gold", description: "The purest expression of understated grandeur. Cream-white cotton meets a thick golden zari border — centuries of tradition distilled into a single, breathtaking drape.", fabric_info: "Handloom Cotton, Gold Zari", image_filename: "kasavu_mundu_gold.jpg", like_count: 389, category: "women", subcategory: "Sarees" },
  { id: "g16", name: "Ajrakh Block-Print Saree — Indigo", description: "Double-sided block printing using a technique older than civilization itself. The geometric symmetry is mathematical, the beauty is spiritual.", fabric_info: "Cotton, Ajrakh Block Print", image_filename: "ajrakh_block_print_indigo.jpg", like_count: 213, category: "women", subcategory: "Sarees", on_sale: true },
  { id: "g17", name: "Handloom Linen Saree — Sage", description: "European linen married to Indian draping. Sage green, crisp yet soft, with a single gold pinstripe along the border. Minimalism with a mother tongue.", fabric_info: "Pure Linen, Gold Thread", image_filename: "handloom_linen_sage.jpg", like_count: 198, category: "women", subcategory: "Sarees" },
  { id: "g18", name: "Resham Thread-Work Saree", description: "Silk threads in forty shades stitched into a garden that never wilts. The embroidery is so raised you can feel the petals — texture as language.", fabric_info: "Georgette, Resham Embroidery", image_filename: "resham_threadwork_saree.jpg", like_count: 267, category: "women", subcategory: "Sarees" },
  { id: "g19", name: "Gold Tissue Bridal Saree", description: "A luminous drape spun from threads of liquid gold. Each motif is a whispered prayer from the weaver's loom — a fabric that doesn't just catch light, it becomes it.", fabric_info: "Pure Gold Tissue, Handwoven", image_filename: "gold_tissue_bridal.jpg", like_count: 512, category: "bridal", subcategory: "Bridal Sarees" },
  { id: "g20", name: "Sambalpuri Ikat Saree", description: "Born in the river-valleys, each thread tie-dyed before being placed on the loom. The resulting geometry has the quality of a half-remembered dream — precise yet fluid.", fabric_info: "Cotton-Silk, Ikat Weave", image_filename: "sambalpuri_ikat.jpg", like_count: 167, category: "women", subcategory: "Sarees", on_sale: true },

  // ── LEHENGAS (10) ──
  { id: "g21", name: "Bridal Lehenga — Royal Maroon", description: "Ten thousand hand-sewn pearls creating rivers of light across raw silk. This is not a garment — it is an inheritance, meant to be passed down through generations.", fabric_info: "Raw Silk, Zardozi & Pearl Work", image_filename: "bridal_lehenga_maroon.jpg", like_count: 623, category: "bridal", subcategory: "Bridal Lehengas" },
  { id: "g22", name: "Gota Patti Festive Lehenga — Pink", description: "Gold ribbon appliqué folded and stitched into petal shapes across every inch. The technique originated in royal workshops — this lehenga carries that DNA.", fabric_info: "Art Silk, Gota Patti Work", image_filename: "gota_patti_lehenga_pink.jpg", like_count: 389, category: "women", subcategory: "Lehengas" },
  { id: "g23", name: "Sequin Wave Lehenga — Champagne", description: "A tsunami of hand-sewn sequins cascading in wave patterns across champagne silk. Under light, it doesn't sparkle — it undulates, like the surface of a golden sea.", fabric_info: "Silk, Hand-sewn Sequins", image_filename: "sequin_lehenga_champagne.jpg", like_count: 445, category: "women", subcategory: "Lehengas" },
  { id: "g24", name: "Benarasi Silk Lehenga — Purple", description: "Purple silk so rich it borders on black, overlaid with gold brocade depicting hunting scenes from Mughal miniatures. A museum piece you're allowed to dance in.", fabric_info: "Benarasi Silk, Gold Brocade", image_filename: "benarasi_lehenga_purple.jpg", like_count: 478, category: "women", subcategory: "Lehengas" },
  { id: "g25", name: "Mirror Work Ghagra Choli", description: "A thousand tiny mirrors catching every flicker of lamplight. Originally crafted for desert festivals, this ghagra turns its wearer into a walking constellation.", fabric_info: "Cotton, Mirror & Thread Work", image_filename: "mirror_work_ghagra.jpg", like_count: 312, category: "women", subcategory: "Lehengas", on_sale: true },
  { id: "g26", name: "Heritage Half-Saree Set — Emerald", description: "The garment of transition — silk-cotton in emerald with a contrasting magenta border. Three pieces, one story of tradition meeting youth.", fabric_info: "Silk-Cotton Blend", image_filename: "heritage_half_saree_emerald.jpg", like_count: 234, category: "women", subcategory: "Lehengas" },
  { id: "g27", name: "Lavani Dance Lehenga — Hot Pink", description: "Vibrant hot pink and parrot green collide in a riot of sequin and mirror work. Designed for movement, celebration, and unapologetic feminine energy.", fabric_info: "Art Silk, Sequin Work", image_filename: "lavani_lehenga_hotpink.jpg", like_count: 289, category: "women", subcategory: "Lehengas", on_sale: true },
  { id: "g28", name: "Pastel Threadwork Lehenga", description: "Soft pastels of mint, lavender, and peach woven together with delicate thread embroidery. Like wearing a spring garden under moonlight.", fabric_info: "Net & Silk, Thread Embroidery", image_filename: "pastel_threadwork_lehenga.jpg", like_count: 356, category: "women", subcategory: "Lehengas" },
  { id: "g29", name: "Brocade Heritage Gown", description: "Brocade from heritage looms, cut into a contemporary floor-length silhouette. Past and present collaborate. A gown for palaces and penthouses.", fabric_info: "Silk Brocade, Zari Weave", image_filename: "brocade_heritage_gown.jpg", like_count: 378, category: "women", subcategory: "Gowns" },
  { id: "g30", name: "Dhakai Jamdani Lehenga Set", description: "Motifs that appear to float above the fabric. The supplementary weft creates patterns so delicate they seem impossible — proof that patience is the ultimate luxury.", fabric_info: "Jamdani Cotton-Silk", image_filename: "dhakai_jamdani_lehenga.jpg", like_count: 213, category: "women", subcategory: "Lehengas" },

  // ── KURTAS & SUITS (10) ──
  { id: "g31", name: "Chikankari Lucknowi Kurta — White", description: "White-on-white embroidery so delicate it looks like frost on fabric. Each stitch is named — tepchi, bakhia, jaali — a vocabulary of shadow and thread.", fabric_info: "Georgette, Chikankari Work", image_filename: "chikankari_lucknowi_white.jpg", like_count: 345, category: "women", subcategory: "Kurtas" },
  { id: "g32", name: "Block-Print Mulmul Kurta Set", description: "Vegetable dyes pressed by hand onto cloud-soft mulmul cotton. Each print carries the fingerprint of the artisan — literally. No two pieces are identical.", fabric_info: "Mulmul Cotton, Block Print", image_filename: "blockprint_mulmul_kurta.jpg", like_count: 178, category: "women", subcategory: "Kurtas", on_sale: true },
  { id: "g33", name: "Hand-Spun Khadi Kurta", description: "The fabric of revolution, reimagined. Hand-spun, hand-woven khadi in its purest form — rough enough to feel real, refined enough for any occasion.", fabric_info: "Hand-Spun Khadi Cotton", image_filename: "handspun_khadi_kurta.jpg", like_count: 167, category: "women", subcategory: "Kurtas" },
  { id: "g34", name: "Mukaish Work Palazzo Set — Mint", description: "Tiny metal pieces pressed flat into fabric, creating a surface that catches starlight. Lucknow's answer to sequins — subtler, older, infinitely more sophisticated.", fabric_info: "Georgette, Mukaish Work", image_filename: "mukaish_palazzo_set_mint.jpg", like_count: 234, category: "women", subcategory: "Suits" },
  { id: "g35", name: "Georgette Sharara Set — Sage", description: "Sage georgette cut into dramatic flared sharara trousers. The silhouette is equal parts grace and rebellion — traditional shape, modern energy.", fabric_info: "Georgette, Thread Work", image_filename: "georgette_sharara_sage.jpg", like_count: 256, category: "women", subcategory: "Suits" },
  { id: "g36", name: "Anarkali Floor-Length Suit — Ivory", description: "Ivory chanderi silk flowing from fitted bodice to floor in an unbroken cascade. Paired with a gold-bordered dupatta that catches the eye like a prayer flag.", fabric_info: "Chanderi Silk, Gold Border", image_filename: "anarkali_ivory_gold.jpg", like_count: 312, category: "women", subcategory: "Suits" },
  { id: "g37", name: "Aari Embroidered Suit — Navy", description: "A hooked needle pulling silk thread from beneath the fabric, creating chain-stitch blooms. The back is as beautiful as the front — craftsmanship that hides nothing.", fabric_info: "Silk, Aari Chain Stitch", image_filename: "aari_embroidered_navy.jpg", like_count: 198, category: "women", subcategory: "Suits", on_sale: true },
  { id: "g38", name: "Silk Angrakha Kurta — Ivory", description: "The wrap-front kurta that predates buttons. Ivory silk tied at the side with handmade dori — the most ancient closure in Indian fashion, still the most elegant.", fabric_info: "Pure Silk, Dori Closure", image_filename: "silk_angrakha_ivory.jpg", like_count: 187, category: "women", subcategory: "Kurtas" },
  { id: "g39", name: "Kalamkari Hand-Painted Suit", description: "Every line drawn with a bamboo pen dipped in natural dye. Mythological scenes unfold across the fabric — gods, demons, and the eternal dance between them.", fabric_info: "Cotton, Kalamkari Painting", image_filename: "kalamkari_handpainted_suit.jpg", like_count: 203, category: "women", subcategory: "Suits" },
  { id: "g40", name: "Cotton Palazzo in Natural Dye", description: "Earth-toned cotton dyed with pomegranate rinds and turmeric. Wide legs that move like poetry. Pockets deep enough for a modern life.", fabric_info: "Organic Cotton, Natural Dye", image_filename: "cotton_palazzo_natural_dye.jpg", like_count: 145, category: "women", subcategory: "Kurtas", on_sale: true },

  // ── MENSWEAR (5) ──
  { id: "g41", name: "Maroon Velvet Sherwani", description: "Structured like armour, soft as a whisper. Maroon velvet with gold thread botanicals climbing from hem to collar. For the man who understands that elegance is a weapon.", fabric_info: "Velvet, Gold Thread Work", image_filename: "maroon_velvet_sherwani.jpg", like_count: 289, category: "men", subcategory: "Sherwanis" },
  { id: "g42", name: "Raw Silk Nehru Jacket — Slate", description: "The silhouette that defined a nation's elegance. Raw silk in slate grey, structured yet fluid, with handmade fabric buttons. Dominates nothing, improves everything.", fabric_info: "Raw Silk, Handmade Buttons", image_filename: "nehru_jacket_slate.jpg", like_count: 167, category: "men", subcategory: "Jackets" },
  { id: "g43", name: "Khadi Silk Jacket — Charcoal", description: "The crunch of khadi, the sheen of silk. A contradiction resolved in charcoal grey. Mandarin collar, invisible stitching — elevates every outfit.", fabric_info: "Khadi Silk Blend", image_filename: "khadi_silk_jacket_charcoal.jpg", like_count: 145, category: "men", subcategory: "Jackets", on_sale: true },
  { id: "g44", name: "Handwoven Dhurrie Jacket", description: "Flat-weave cotton transformed into structured outerwear. The geometric patterns are ancestral maps — diamonds for seeds, zigzags for water. Wearable cartography.", fabric_info: "Cotton Dhurrie Weave", image_filename: "dhurrie_weave_jacket.jpg", like_count: 134, category: "men", subcategory: "Jackets" },
  { id: "g45", name: "Lucknowi Kurta Pajama — White", description: "Chikankari embroidery on cotton so fine it breathes. The ultimate Indian summer garment — white on white, shadow on light, cool against warm skin.", fabric_info: "Cotton, Chikankari Embroidery", image_filename: "lucknowi_kurta_white.jpg", like_count: 223, category: "men", subcategory: "Kurtas" },

  // ── DUPATTAS & SHAWLS (5) ──
  { id: "g46", name: "Phulkari Embroidered Dupatta", description: "Flower-work so dense you can barely see the base fabric. Bright silk threads on cotton — originally stitched by brides in stolen moments of anticipation.", fabric_info: "Cotton, Silk Thread Phulkari", image_filename: "phulkari_dupatta.jpg", like_count: 234, category: "accessories", subcategory: "Dupattas" },
  { id: "g47", name: "Pashmina Shawl — Midnight Garden", description: "Three hundred hours of needlework on the finest Himalayan pashmina. Roses, irises, and chinar leaves bloom in an eternal spring you can wear.", fabric_info: "Pure Pashmina, Needle Work", image_filename: "pashmina_midnight_garden.jpg", like_count: 378, category: "accessories", subcategory: "Shawls" },
  { id: "g48", name: "Zari-Bordered Silk Dupatta — Plum", description: "Pure silk dyed to the colour of ripe plums. A thick zari border in real gold adds gravity to the lightest fabric.", fabric_info: "Pure Silk, Real Gold Zari", image_filename: "zari_silk_dupatta_plum.jpg", like_count: 198, category: "accessories", subcategory: "Dupattas" },
  { id: "g49", name: "Kantha Embroidered Wrap", description: "Running stitches telling stories. Born from layering old saris together, Kantha transforms recycled fabric into narrative art. Every stitch a word.", fabric_info: "Cotton, Kantha Stitch", image_filename: "kantha_embroidered_wrap.jpg", like_count: 167, category: "accessories", subcategory: "Shawls", on_sale: true },
  { id: "g50", name: "Bandhani Silk Dupatta — Saffron", description: "Saffron silk knotted ten thousand times, then dipped in dye. A galaxy of dots creating paisley universes. Each knot a meditation.", fabric_info: "Silk, Bandhani Tie-Dye", image_filename: "bandhani_silk_saffron.jpg", like_count: 212, category: "accessories", subcategory: "Dupattas" },

  // ── JEWELRY (7) ──
  { id: "g51", name: "Kundan Bridal Set — Polki Diamonds", description: "Uncut diamonds set in gold using the Kundan technique — no claws, no prongs, just gold foil embracing each stone. Mughal perfection, preserved.", fabric_info: "Gold, Polki Diamonds", image_filename: "kundan_set_polki.jpg", like_count: 534, category: "bridal", subcategory: "Bridal Jewelry" },
  { id: "g52", name: "Temple Choker Neckpiece — Gold", description: "Gold-plated temple jewelry featuring Lakshmi in her full glory. Originally crafted for temple dancers, now for women who understand adornment as devotion.", fabric_info: "Gold-Plated Silver, Pearls", image_filename: "temple_choker_gold.jpg", like_count: 412, category: "accessories", subcategory: "Jewelry" },
  { id: "g53", name: "Filigree Silver Jhumkas", description: "Silver twisted into threads finer than hair, then sculpted into bell-shaped earrings. When you move, they whisper. An heirloom disguised as an accessory.", fabric_info: "Sterling Silver, Filigree", image_filename: "filigree_silver_jhumkas.jpg", like_count: 289, category: "accessories", subcategory: "Jewelry", on_sale: true },
  { id: "g54", name: "Bridal Nath — Gold & Pearl", description: "A crescent of gold connecting ear to nostril with a chain of pearls. Once a mark of matrimony, now a mark of anyone bold enough to wear heritage on their face.", fabric_info: "Gold-Plated, Fresh Pearls", image_filename: "bridal_nath_gold_pearl.jpg", like_count: 345, category: "bridal", subcategory: "Bridal Jewelry" },
  { id: "g55", name: "Jadau Maang Tikka", description: "A single pendant of gold and uncut gems resting at the crown. In traditional belief, this is the seat of the sixth chakra — jewelry as spiritual armour.", fabric_info: "Gold, Uncut Precious Stones", image_filename: "jadau_maang_tikka.jpg", like_count: 312, category: "accessories", subcategory: "Jewelry" },
  { id: "g56", name: "Lacquer Bangles — Ruby & Gold", description: "Twelve bangles hand-painted in layers of ruby lacquer and gold leaf. When they clink, they make the sound that has accompanied every Indian celebration.", fabric_info: "Lacquer, Gold Leaf", image_filename: "lacquer_bangles_ruby.jpg", like_count: 178, category: "accessories", subcategory: "Jewelry" },
  { id: "g57", name: "Coin Antique Necklace", description: "Old coins reimagined as jewelry. Each disc hand-stamped with lotus motifs, linked into a cascade. History measured in the weight of gold around your neck.", fabric_info: "Gold-Plated Brass, Antique", image_filename: "coin_antique_necklace.jpg", like_count: 256, category: "accessories", subcategory: "Jewelry" },

  // ── BAGS & CLUTCHES (3) ──
  { id: "g58", name: "Zardozi Clutch — Midnight Blue", description: "Metallic thread and semi-precious stones arranged in floral arabesques on midnight silk. A tiny gallery of craftsmanship you can hold in your palm.", fabric_info: "Silk, Zardozi & Stone Work", image_filename: "zardozi_clutch_midnight.jpg", like_count: 189, category: "accessories", subcategory: "Bags" },
  { id: "g59", name: "Brocade Potli Bag — Emerald", description: "A handful of heritage. Emerald brocade gathered into the traditional drawstring form, finished with gold tassels. Inside, a silk lining the colour of champagne.", fabric_info: "Silk Brocade, Gold Tassels", image_filename: "brocade_potli_emerald.jpg", like_count: 156, category: "accessories", subcategory: "Bags", on_sale: true },
  { id: "g60", name: "Hand-Carved Sandalwood Clutch", description: "A block of sandalwood, carved into a clutch that releases fragrance with the warmth of your hand. Part accessory, part aromatherapy, entirely unforgettable.", fabric_info: "Sandalwood, Brass Clasp", image_filename: "sandalwood_clutch_carved.jpg", like_count: 134, category: "accessories", subcategory: "Bags" },
];

export default garments;
